spring.application.name=employee-service
server.port=9989
teaql.ensureTable=true
teaql.contextClass=com.philipgreat.mcme.CustomUserContext

server.tomcat.connection-timeout=20000
server.tomcat.max-connections=200
server.tomcat.max-threads=200
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:./employee-service-02.db
spring.datasource.type=org.springframework.jdbc.datasource.SimpleDriverDataSource

spring.datasource.hikari.initialization-fail-timeout=0





